services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "9090:9090"
    environment:
      MONGO_URL: mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Users?retryWrites=true&w=majority&appName=Morrow
      GPASSWORD: dhaupxvdrvjptfpb
      GMAIL: morrowshp@gmail.com
      GOOGLE_CLIENT_ID: 830837464571-lb91s99nkkbaghpoidd1pn8ijjq61ov3.apps.googleusercontent.com
      GITHUB_CLIENT_ID: Ov23liQLEQjkuY7FHHPO
      GITHUB_CLIENT_SECRET: 29f46230258fdb0112f5a39877626f05f3aa1da6
    networks:
      - morrow_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Users?retryWrites=true&w=majority&appName=Morrow
      - PORT=3000
      - RABBITMQ_URI=amqps://rhmgxucz:U_il_-AzOWJjRnm5seFTFe_gfII8J3eF@puffin.rmq2.cloudamqp.com/rhmgxucz
      - JWT_SECRET=secret_key
      - GMAIL=morrowshp@gmail.com
      - GPASSWORD=dhaupxvdrvjptfpb
      - GITHUB_CLIENT_ID=Ov23liQLEQjkuY7FHHPO
      - GITHUB_CLIENT_SECRET=02e4bb399e68fad50b85077cbfaccc9c9e95286f
    depends_on:
      - rabbitmq
    networks:
      - morrow_network
    restart: on-failure

  project-service:
    build:
      context: ./project-service
      dockerfile: Dockerfile
    container_name: project-service
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:Hashim1002*1002@db.qdzoczdtydcgijzuoeqf.supabase.co:5432/postgres
      - RABBITMQ_URI=amqps://rhmgxucz:U_il_-AzOWJjRnm5seFTFe_gfII8J3eF@puffin.rmq2.cloudamqp.com/rhmgxucz
    depends_on:
      - rabbitmq
    networks:
      - morrow_network
    restart: on-failure

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Tasks?retryWrites=true&w=majority&appName=Morrow
      - RABBITMQ_URI=amqps://rhmgxucz:U_il_-AzOWJjRnm5seFTFe_gfII8J3eF@puffin.rmq2.cloudamqp.com/rhmgxucz
      - PORT=5000
    networks:
      - morrow_network

  communication-service:
    build:
      context: ./communication-service
      dockerfile: Dockerfile
    container_name: communication-service
    ports:
      - "2000:2000"
    environment:
      PORT=2000
      MONGO_URL=mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Communications?retryWrites=true&w=majority&appName=Morrow
      REDISPORT=21418
      REDISHOST=redis-hashimkakkaden-13b4.c.aivencloud.com
      REDISPASS=AVNS_yik9T3mkISHuVz6SunL
      REDISUSER=default
      RABBITMQ_URL=amqps://rhmgxucz:U_il_-AzOWJjRnm5seFTFe_gfII8J3eF@puffin.rmq2.cloudamqp.com/rhmgxucz
    networks:
      - morrow_network
networks:
  morrow_network:
    driver: bridge