services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - morrow_network
    environment:
      - RABBITMQ_DEFAULT_USER=hashim
      - RABBITMQ_DEFAULT_PASS=hashim
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "9090:9090"
    environment:
      MONGO_URL: mongodb://mongo:27017/Users
      GPASSWORD: dhaupxvdrvjptfpb
      GMAIL: morrowshp@gmail.com
      GOOGLE_CLIENT_ID: 830837464571-lb91s99nkkbaghpoidd1pn8ijjq61ov3.apps.googleusercontent.com
      GITHUB_CLIENT_ID: Ov23liQLEQjkuY7FHHPO
      GITHUB_CLIENT_SECRET: 29f46230258fdb0112f5a39877626f05f3aa1da6
    depends_on:
      - user-mongo
    networks:
      - morrow_network
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://localhost:27017/Users
      - PORT=3000
      - RABBITMQ_URI=amqp://hashim:hashim@rabbitmq:5673
      - JWT_SECRET=secret_key
      - GMAIL=morrowshp@gmail.com
      - GPASSWORD=dhaupxvdrvjptfpb
      - GITHUB_CLIENT_ID=Ov23liQLEQjkuY7FHHPO
      - GITHUB_CLIENT_SECRET=02e4bb399e68fad50b85077cbfaccc9c9e95286f
    depends_on:
      - user-mongo
    networks:
      - morrow_network
  project-service:
    build:
      context: ./project-service
      dockerfile: Dockerfile
    container_name: project-service
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:hashim1002@db:5432/Morrow
      - RABBITMQ_URI=amqp://hashim:hashim@rabbitmq:5673
    depends_on:
      - project-postgres
    networks:
      - morrow_network
  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://localhost:27017/Tasks
      - RABBITMQ_URI=amqp://hashim:hashim@rabbitmq:5673
      - PORT=5000
    networks:
      - morrow_network
  communication-service:
    build:
      context: ./communication-service
      dockerfile: Dockerfile
    container_name: communication-service
    ports:
      - "2000:2000"
    environment:
      - MONGO_URL=mongodb://localhost:27017/Communication
      - PORT=2000
      - RABBITMQ_URI=amqp://hashim:hashim@rabbitmq:5673
    networks:
      - morrow_network
    depends_on:
      - communication-mongo


  project-postgres:
    image: postgres:latest
    container_name: project-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hashim1002
      - POSTGRES_DB=Morrow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - morrow_network
    ports:
      - "5432:5432"
  user-mongo:
    image: mongo:6.0
    container_name: user-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Users
    networks:
      - morrow_network
  task-mongo:
    image: mongo:6.0
    container_name: task-mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Tasks
    networks:
      - morrow_network
  communication-mongo:
    image: mongo:6.0
    container_name: communication-mongo
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Communication
    networks:
      - morrow_network
volumes:
  mongo-data:
  rabbitmq_data:
  postgres-data:


networks:
  morrow_network:
    driver: bridge
