services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - morrow_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - morrow_network
    command: redis-server --requirepass mysecretpassword
    environment:
     REDIS_PASSWORD: mysecretpassword
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      USER_SERVICE: http://user-service:3000
      COMMUNICATION_SERVICE: http://communication-service:2000
      TASK_SERVICE: http://task-service:5000
      AUTH_SERVICE: http://auth-service:9090
      PROJECT_SERVICE: http://project-service:4000
    networks:
      - morrow_network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "9090:9090"
    environment:
      MONGO_URL: mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Users?retryWrites=true&w=majority&appName=Morrow
      GPASSWORD: dhaupxvdrvjptfpb
      GMAIL: morrow.shp@gmail.com
      GOOGLE_CLIENT_ID: 830837464571-lb91s99nkkbaghpoidd1pn8ijjq61ov3.apps.googleusercontent.com
      GITHUB_CLIENT_ID: Ov23liQLEQjkuY7FHHPO
      GITHUB_CLIENT_SECRET: 29f46230258fdb0112f5a39877626f05f3aa1da6
    networks:
      - morrow_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      MONGO_URL: mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Users?retryWrites=true&w=majority&appName=Morrow
      PORT: 3000
      RABBITMQ_URI: amqp://rabbitmq:5672
      JWT_SECRET: secret_key
      GMAIL: morrowshp@gmail.com
      GPASSWORD: dhaupxvdrvjptfpb
      GITHUB_CLIENT_ID: Ov23liQLEQjkuY7FHHPO
      GITHUB_CLIENT_SECRET: 02e4bb399e68fad50b85077cbfaccc9c9e95286f
      GRPC_PROJECT_SERVICE_URI: project-service:7070
    depends_on:
      - rabbitmq
    networks:
      - morrow_network
    restart: on-failure

  project-service:
    build:
      context: ./project-service
      dockerfile: Dockerfile
    container_name: project-service
    ports:
      - "4000:4000"
      - "7070:7070"
    environment:
      DATABASE_URL: postgres://avnadmin:AVNS_7l_ZOpVFIasK0V6jCyS@pg-161e3054-hashimkakkaden-13b4.c.aivencloud.com:21417/defaultdb?sslmode=require
      RABBITMQ_URI: amqp://rabbitmq:5672
      GRPC_USER_SERVICE_URI: user-service:8080
    depends_on:
      - rabbitmq
    networks:
      - morrow_network
    restart: on-failure

  communication-service:
    build:
      context: ./communication-service
      dockerfile: Dockerfile
    container_name: communication-service
    ports:
      - "2000:2000"
    environment:
      PORT: 2000
      MONGO_URL: mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Communications?retryWrites=true&w=majority&appName=Morrow
      REDISPORT: 6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDISHOST: redis
      REDISUSER: default
      REDISPASS: mysecretpassword
    depends_on:
      - rabbitmq
      - redis
    networks:
      - morrow_network
    restart: on-failure

  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb+srv://hashimkakkadan1:o2nLlfKiJ9boV7Ns@morrow.pcq64.mongodb.net/Tasks?retryWrites=true&w=majority&appName=Morrow
      RABBITMQ_URI: amqp://rabbitmq:5672
      PORT: 5000
    depends_on:
      - rabbitmq
    networks:
      - morrow_network
  # frontend:
  #   build:
  #     context: ./Morrow-Frontend
  #     dockerfile: Dockerfile
  #   container_name: morrow-frontend
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - api-gateway
  #   networks:
  #     - morrow_network

networks:
  morrow_network:
    driver: bridge
