apiVersion: v1
kind: Secret
metadata:
  name: general-secret
type: Opaque
data:
  RABBITMQ_URI: YW1xcDovL2FkbWluOmFkbWluMTIzQHJhYmJpdG1xOjU2NzE=  
  MONGO_URL: bW9uZ29kYjovL2hhc2hpbWtha2thZGFuOkhhc2hpbTEwMDJAbW9uZ29kYi1zZXJ2aWNlOjI3MDE3L1VzZXJz
  JWT_SECRET: c2VjcmV0and0S2V5  
  GMAIL: bW9ycm93c2hwQGdtYWlsLmNvbQ==  
  GPASSWORD: bW9ycm93c2hwQGdtYWlsLmNvbQ==  
  GITHUB_CLIENT_ID: T3YyM2xpUUxFUWprdVk3RkhIUE8=  
  GITHUB_CLIENT_SECRET: MDJlNGJiMzk5ZTY4ZmFkNTBiODUwNzdjYmZhY2NjOWM5ZTk1Mjg2Zg==
  GRPC_PROJECT_SERVICE_URI: cHJvamVjdC1zZXJ2aWNlOjcwNzA=
  GRPC_USER_SERVICE_URI: dXNlci1zZXJ2aWNlOjgwODA=