apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        rollme: "{{randAlphaNum 5}}"
    spec:
      containers:
        - name: gateway
          image: hashme7/morrow-gateway:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: general-secret