apiVersion: apps/v1
kind: Deployment 
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        rollme: "{{randAlphaNum 5}}"
    spec:
      containers:
        - name: auth-service
          image: hashme7/morrow-auth-service:latest
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: general-secret