apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
      annotations:
        rollme: "{{randAlphaNum 5}}"
    spec:
      containers:
        - name: communication-service
          image: hashme7/morrow-communication-service:latest
          ports:
            - containerPort: 2000
          env:
            - name: MONGO_URL
              value: "mongodb://hashimkakkaden:Hashim1002@mongodb-service:27017/Communication"
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: RABBITMQ_URI
            - name: REDISPORT
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: REDIS_PORT
            - name: REDISHOST
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: REDIS_HOST
            - name: REDISUSER
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: REDIS_USER
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: general-secret
                  key: RABBITMQ_URI

