apiVersion: apps/v1
kind: Deployment 
metadata:
  name: task-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: task-service 
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: hashme7/morrow-task-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb://hashimkakkaden:Hashim1002@mongodb-service:27017/Tasks"