apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        rollme: "{{randAlphaNum 5}}"
    spec:
      containers:
        - name: user-service
          image: hashme7/morrow-user-service:latest
          ports:  
            - containerPort: 3000
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: general-secret