apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project-service
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: grpc 
      protocol: TCP
      port: 7070      
      targetPort: 7070
  type: ClusterIP 